# Generated by Django 3.0.3 on 2020-02-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_date', models.DateTimeField(verbose_name='Date recorded')),
                ('amount', models.FloatField(default=0.0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverity_data.Campaign')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverity_data.Datasource')),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_date', models.DateTimeField(verbose_name='Date recorded')),
                ('amount', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverity_data.Campaign')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverity_data.Datasource')),
            ],
        ),
        migrations.AddIndex(
            model_name='impression',
            index=models.Index(fields=['rec_date', 'datasource', 'campaign'], name='adverity_da_rec_dat_41976a_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['rec_date', 'datasource', 'campaign'], name='adverity_da_rec_dat_ac596b_idx'),
        ),
    ]
